version: '3.7'
services:
  redis:
    image: redis:alpine
  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: patrick
      POSTGRES_DB: atlas_of_thrones
    volumes:
      - type: bind
        source: ./atlas_of_thrones.sql
        target: /docker-entrypoint-initdb.d/atlas_of_thrones.sql
  atlas:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    command: ./wait-for.sh postgres:5432 -- npm run dev
